name: Deploy

on:
  push:
    branches:
      - development

jobs:
  build:
    runs-on: ubuntu-latest
    
    strategy:
      matrix:
        node-version: [14.x]
    
    steps:
      - uses: actions/checkout@v2
      - name: Instalar dependências
        run: yarn install
      
      - name: Compilar para javascript
        run: yarn tsc

      - name: Rodar os testes 
        run: yarn test
        
      - uses: akhileshns/heroku-deploy@v3.8.8 # This is the action
        with:
          heroku_api_key: ${{secrets.HEROKU_API_KEY}}
          heroku_app_name: "firstplayerwinner" #Must be unique in Heroku
          heroku_email: ${{secrets.HEROKU_EMAIL}}
          procfile: "web: yarn start:prod"
