name: check
on:
  push:
    branches: [ development ]
  pull_request:
    branches: [ development ]

jobs:
  build:
    runs-on: ubuntu-18.04
    
    strategy:
      matrix:
        node-version: [8.x]

    steps:
      - uses: actions/checkout@v2

      - name: Instalar dependências
        run: yarn install
      
      - name: Compilar para javascript
        run: yarn tsc

      - name: Rodar os testes 
        run: yarn test
